//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by HealthCardReader.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_HEALTHCARDREADER_DIALOG     102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_WRITE_PUBLISHINFO    129
#define IDD_DIALOG_WRITE_PERSONINFO     130
#define IDD_DIALOG_WRITE_OWNERINFO      131
#define IDD_DIALOG_WRITE_ADDRINFO       132
#define IDD_DIALOG_WRITE_RELATIVEINFO   133
#define IDD_DIALOG_WRITE_JOBMARRYINFO   134
#define IDD_DIALOG_WRITE_LICENCEINFO    135
#define IDD_DIALOG_WRITE_CLINICALINFO   136
#define IDD_DIALOG_WRITE_SPECIALINFO    137
#define IDD_DIALOG_WRITE_ALLERGY_RECORD 138
#define IDD_DIALOG_WRITE_IMMUNE_RECORD  139
#define IDC_BTN_CONNECT_DEV             1000
#define IDC_EDIT_DATA                   1001
#define IDC_BTN_CLOSE_DEV               1002
#define IDC_BTN_PSAM_ON                 1003
#define IDC_BTN_VERIFY_PIN              1004
#define IDC_EDIT_PIN                    1005
#define IDC_BTN_HEALTH_ON               1006
#define IDC_BTN_READ_PUBLISHINFO        1007
#define IDC_BTN_WRITE_PUBLISHINFO       1008
#define IDC_EDIT_KLB                    1008
#define IDC_EDIT_GFBB                   1009
#define IDC_BTN_READ_PERSONINFO         1009
#define IDC_EDIT_FKJGMC                 1010
#define IDC_BTN_WRITE_PERSONINFO        1010
#define IDC_EDIT_AQM                    1011
#define IDC_BTN_READ_PIC                1011
#define IDC_EDIT_YYCSDM                 1012
#define IDC_BTN_WRITE_PIC               1012
#define IDC_EDIT_XPXLH                  1013
#define IDC_BTN_PSAM_PUB                1013
#define IDC_EDIT_FKJGDM                 1014
#define IDC_BTN_READ_OWNERINFO          1014
#define IDC_EDIT_FKJGZS                 1015
#define IDC_BTN_WRITE_OWNERINFO         1015
#define IDC_EDIT_FKSJ                   1016
#define IDC_BTN_READ_ADDRINFO           1016
#define IDC_EDIT_KH                     1017
#define IDC_BTN_WRITE_ADDRINFO          1017
#define IDC_BTN_WRITE                   1018
#define IDC_BTN_READ_JOBMARRYINFO       1018
#define IDC_EDIT_XM                     1019
#define IDC_BTN_WRITE_JOBMARRYINFO      1019
#define IDC_EDIT_QGYZBZ                 1019
#define IDC_EDIT_XB                     1020
#define IDC_BTN_READ_RELATIVEINFO       1020
#define IDC_EDIT_QGQSBZ                 1020
#define IDC_EDIT_MZ                     1021
#define IDC_BTN_WRITE_RELATIVEINFO      1021
#define IDC_EDIT_KZXYZBZ                1021
#define IDC_EDIT_CSRQ                   1022
#define IDC_BTN_READ_LICENCEINFO        1022
#define IDC_EDIT_XZQBQBZ                1022
#define IDC_EDIT_SFZH                   1023
#define IDC_BTN_WRITE_LICENCEINFO       1023
#define IDC_EDIT_QTYXJSMC               1023
#define IDC_EDIT_KYXQ                   1024
#define IDC_BTN_READ_CLINICALINFO       1024
#define IDC_EDIT_BRDTH1                 1025
#define IDC_BTN_WRITE_CLINICALINFO      1025
#define IDC_EDIT_BRDTH2                 1026
#define IDC_BTN_READ_SPECIALINFO        1026
#define IDC_EDIT_YLFYZFFS1              1027
#define IDC_BTN_WRITE_SPECIALINFO       1027
#define IDC_EDIT_YLFYZFFS2              1028
#define IDC_BTN_READ_ALLERGY_RECORD     1028
#define IDC_EDIT_YLFYZFFS3              1029
#define IDC_BTN_READ_IMMUNE_RECORD      1029
#define IDC_EDIT_DZLB1                  1030
#define IDC_BTN_ADD_ALLERGY_RECORD      1030
#define IDC_EDIT_DZ1                    1031
#define IDC_BTN_ADD_IMMUNE_RECORD       1031
#define IDC_EDIT_DZLB2                  1032
#define IDC_BTN_READ_INHOSPITAL_RECORD  1032
#define IDC_EDIT_DZ2                    1033
#define IDC_BTN_WRITE_INHOSPITAL_RECORD 1033
#define IDC_BTN_CLEAR_INHOSPITAL_RECORD 1034
#define IDC_BTN_READ_OUTPATIENT_RECORD  1035
#define IDC_BTN_WRITE_OUTPATIENT_RECORD 1036
#define IDC_BTN_CLEAR_OUTPATIENT_RECORD 1037
#define IDC_BTN_PSAM_TERMINAL           1038
#define IDC_BTN_PSAM_PUBAPP             1039
#define IDC_BTN_PSAM_ORCER              1040
#define IDC_BTN_PSAM_CER                1041
#define IDC_EDIT_LXRXM1                 1044
#define IDC_EDIT_LXRGX1                 1045
#define IDC_EDIT_LXRDH1                 1046
#define IDC_EDIT_LXRXM2                 1047
#define IDC_EDIT_LXRGX2                 1048
#define IDC_EDIT_LXRDH2                 1049
#define IDC_EDIT_LXRXM3                 1050
#define IDC_EDIT_LXRGX3                 1051
#define IDC_EDIT_LXRDH3                 1052
#define IDC_EDIT_WHCD                   1053
#define IDC_EDIT_HYZK                   1054
#define IDC_EDIT_ZY                     1055
#define IDC_EDIT_ZJLB                   1056
#define IDC_EDIT_ZJHM                   1057
#define IDC_EDIT_JKDAH                  1058
#define IDC_EDIT_XNHZH                  1059
#define IDC_EDIT_ABOXX                  1070
#define IDC_EDIT_RHXX                   1071
#define IDC_EDIT_XZBBZ                  1072
#define IDC_EDIT_XNXGBBZ                1073
#define IDC_EDIT_DXBBZ                  1074
#define IDC_EDIT_NXWLBZ                 1075
#define IDC_EDIT_TNBBZ                  1076
#define IDC_EDIT_QGYBZ                  1077
#define IDC_EDIT_TXBZ                   1078
#define IDC_EDIT_JSBBZ                  1079
#define IDC_COMBO_ALLERGY_RECORD        1080
#define IDC_EDIT_XCBZ                   1081
#define IDC_COMBO_IMMUNE_RECORD         1081
#define IDC_EDIT_GMWZMC                 1082
#define IDC_COMBO_INHOSPITAL_RECORD     1082
#define IDC_EDIT_GMFY                   1083
#define IDC_COMBO_INHOSPITAL_RECORD2    1083
#define IDC_EDIT_MYJZMC                 1084
#define IDC_COMBO_INHOSPITAL_INFO       1084
#define IDC_EDIT_MYJZSJ                 1085
#define IDC_COMBO_OUTPATIENT_INFO       1085
#define IDC_EDIT_INHOSPITAL_DATA        1086
#define IDC_BTN_READ_INHOSPITALINFO     1087
#define IDC_BTN_WRITE_INHOSPITALINFO    1088
#define IDC_BTN_READ_ALLINHOSPITALINFO  1089
#define IDC_BTN_WRITE_ALLINHOSPITALINFO 1090
#define IDC_EDIT_OUTPATIENT_DATA        1091
#define IDC_BTN_READ_OUTPATIENTINFO     1092
#define IDC_BTN_WRITE_OUTPATIENTINFO    1093
#define IDC_BTN_READ_ALLOUTPATIENTINFO  1094
#define IDC_BTN_WRITE_ALLINHOSPITALINFO2 1095
#define IDC_BTN_WRITE_ALLOUTPATIENTINFO 1095

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1088
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
