//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by InterfaceDemo.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_INTERFACEDEMO_DIALOG        102
#define IDR_MAINFRAME                   128
#define IDD_DIALOG_input                129
#define IDD_DIALOG_input2               130
#define IDD_DIALOG_PSAM                 131
#define IDC_LIST                        1000
#define IDC_STATIC_FK_BASEINFO          1001
#define IDC_BUTTON_CB_READ              1002
#define IDC_BUTTON_FK_READ              1002
#define IDC_BUTTON_CB_WRITE             1003
#define IDC_BUTTON_FK_WRITE             1003
#define IDC_BUTTON_CB_READ2             1004
#define IDC_STATIC_CKR_BASEINFO         1006
#define IDC_BUTTON_OPEN                 1007
#define IDC_BUTTON_CLOSE                1008
#define IDC_STATIC_GM                   1009
#define IDC_BUTTON_GM_READ              1010
#define IDC_STATIC_MYJZ                 1011
#define IDC_BUTTON_MY_READ              1012
#define IDC_BUTTON_ZZJLBS_READ          1013
#define IDC_STATIC_ZZJLBS               1014
#define IDC_STATIC_MZJLBS               1015
#define IDC_BUTTON_MZJLBS_READ          1016
#define IDC_STATIC_ZYXX                 1017
#define IDC_BUTTON_ZYXX                 1018
#define IDC_STATIC_MZJLXX               1019
#define IDC_BUTTON_MZXX_READ            1020
#define IDC_STATIC_DIZHI                1021
#define IDC_BUTTON_DIZHI_READ           1022
#define IDC_STATIC_LXR                  1023
#define IDC_BUTTON_LXR_READ             1024
#define IDC_STATIC_HY                   1025
#define IDC_BUTTON_ZYHY_READ            1026
#define IDC_STATIC_ZJXX                 1027
#define IDC_BUTTON_ZJJLXX_READ          1028
#define IDC_STATIC_LCJBSJ               1029
#define IDC_BUTTON_LCJBSJ_READ          1030
#define IDC_STATIC_TSXX                 1031
#define IDC_BUTTON_TSXX_READ            1032
#define IDC_BUTTON_CKRJBXX_WRITE        1033
#define IDC_BUTTON_GM_WRITE             1034
#define IDC_BUTTON_MYJBSJ_WRITE         1035
#define IDC_BUTTON_ZYJL_WRITE           1036
#define IDC_BUTTON_ZZJLYX_ERASE         1037
#define IDC_BUTTON_MZJLBS_WRITE         1038
#define IDC_BUTTON_MZJLBS_ERASE         1039
#define IDC_BUTTON_ZYXX_WRITE           1040
#define IDC_BUTTON_MZXX_WRITE           1041
#define IDC_BUTTON_DZXX_WRITE           1042
#define IDC_BUTTON_LXRXX_WRITE          1043
#define IDC_BUTTON1_ZYHYXX_WRITE        1044
#define IDC_BUTTON_ZJJLXX_WRITE         1045
#define IDC_BUTTON_LCJBSJ_WRITE         1046
#define IDC_BUTTON_TSXXSJ_WRITE         1047
#define IDC_BUTTON_errmsg               1048
#define IDC_BUTTON_MZ_SIGN              1049
#define IDC_BUTTON_PSAM                 1050
#define IDC_BUTTON_ZY_SIGN              1051
#define IDC_STATIC_ZY_WDATA             1052
#define IDC_EDIT_ZY_WDATA               1053
#define IDC_BUTTON_RESET                1054
#define IDC_BUTTON_RESETPSAM            1055
#define IDC_BUTTON_RESET3               1056
#define IDC_BUTTON_READ_SAM_ORGCER      1057
#define IDC_STATIC_MZ_WDATA             1060
#define IDC_EDIT_MZ_WDATA               1061
#define IDC_BUTTON_ZP_READ              1064
#define IDC_STATIC_DIZHI2               1065
#define IDC_BUTTON_WSB_READ             1066
#define IDC_BUTTON_WSB_WRITE            1067
#define IDC_BUTTON_ZP_WRITE             1068
#define IDC_BUTTON_HASH                 1069
#define IDC_BUTTON_WSB_OPEN             1070
#define IDC_BUTTON_HASH2                1070
#define IDC_BUTTON_WSB_CLOSE            1071
#define IDC_BUTTON_HASH3                1071
#define IDC_STATIC_NUMBER               1072
#define IDC_BUTTON_DIZHI_READ2          1073
#define IDC_EDIT1                       1073
#define IDC_BUTTON_DZXX_WRITE2          1074
#define IDC_STATIC1                     1074
#define IDC_EDIT_OldPIN                 1074
#define IDC_STATIC_DIZHI3               1075
#define IDC_STATIC2                     1075
#define IDC_BUTTON1                     1075
#define IDC_STATIC_ZY_POS2              1076
#define IDC_EDIT2                       1076
#define IDC_BUTTON2                     1076
#define IDC_STATIC3                     1077
#define IDC_COMBO_ZYID                  1077
#define IDC_BUTTON3                     1077
#define IDC_STATIC_ZY_POS3              1078
#define IDC_EDIT3                       1078
#define IDC_BUTTON4                     1078
#define IDC_STATIC4                     1079
#define IDC_COMBO_MZID                  1079
#define IDC_BUTTON5                     1079
#define IDC_EDIT4                       1080
#define IDC_COMBO_ZYBZID                1080
#define IDC_BUTTON6                     1080
#define IDC_STATIC5                     1081
#define IDC_COMBO_MZBZID                1081
#define IDC_BUTTON7                     1081
#define IDC_EDIT5                       1082
#define IDC_STATIC_ZY_POS4              1082
#define IDC_STATIC6                     1083
#define IDC_STATIC_ZY_POS5              1083
#define IDC_EDIT_PIN                    1083
#define IDC_EDIT6                       1084
#define IDC_COMBO_GMID                  1084
#define IDC_EDIT_NewPIN                 1084
#define IDC_STATIC7                     1085
#define IDC_STATIC_ZY_POS6              1085
#define IDC_EDIT7                       1086
#define IDC_COMBO_MYID                  1086
#define IDC_STATIC8                     1087
#define IDC_STATIC_ZY_POS7              1087
#define IDC_EDIT8                       1088
#define IDC_EDIT_OUT                    1088
#define IDC_STATIC9                     1089
#define IDC_STATIC_ZY_WDATA2            1089
#define IDC_EDIT9                       1090
#define IDC_STATIC10                    1091
#define IDC_EDITPIN                     1091
#define IDC_EDIT10                      1092
#define IDC_CITYCODE                    1092
#define IDC_STATIC11                    1093
#define IDC_CHECK1                      1093
#define IDC_EDIT11                      1094
#define IDC_READALL                     1094
#define IDC_STATIC12                    1095
#define IDC_WRITEALL                    1095
#define IDC_EDIT12                      1096
#define IDC_READEDLL                    1096
#define IDC_STATIC13                    1097
#define IDC_WRITEEDLL                   1097
#define IDC_EDIT13                      1098
#define IDC_STATIC14                    1099
#define IDC_EDIT14                      1100
#define IDC_STATIC15                    1101
#define IDC_EDIT15                      1102

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        132
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1098
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
